### ISSUE TITLE
[BUG] Multicard double switch

### ISSUE THREAD

**Issue by StaffordBully** [mennovanhout/flutter-hdashboards-issues#123]
**Describe the bug**
Now when background color is added i cant use my double switches anymore.
Before that i added my double switch and could turn on/off output 1 and 2 separate.
Now only output on can be turned on/off even when i click output 2

**Expected behavior**
when added a device with multiple buttons, enable that buttons can set on/off separate like in v0.4.1+18
Than it worked great

**Using information (please complete the following information):**
 - OS: [Android, Windows]
 - Browser [Chrome]
 - Version [Android app v0.4.3+20, web version v0.4.3+20]

**Comment by mennovanhout** [comment]
Fixed in v0.4.4

**Comment by StaffordBully** [comment]
Still not working.

If I add my switch in multicard

Output 1
Output 2

I click on Output 1 then switches 1
When I click on Output 2 then switches 1 also background and color are wrong

**Comment by mennovanhout** [comment]
Ah that's another issue than i anticipated for.
If you really really click on the switch and not next to the switch what happens than?

**Comment by mennovanhout** [comment]
Thanks for letting me use your device, fixed in v0.4.5
